### ISSUE TITLE
dtNodePool Asserts always seem to fail

### ISSUE THREAD

**Issue by nt153133** [ryancheung/RecastSharp#1]
I may be misunderstanding this but if I do 

```cs
dtNavMeshQuery naviMeshQuery = DetourCommon.dtAllocNavMeshQuery();
naviMeshQuery.init(navMesh, 2048);
```

I get an assert failed on `DetourNode.cs:line 37`. Looking at DetourNode I can't find anywhere that `m_maxNodes` is set before the assert, If the lines
```cs
this.m_maxNodes = maxNodes;
this.m_hashSize = hashSize;
this.m_nodeCount = 0;
```
are moved before the asserts there is no problem. Am I initializing the `dtNavMeshQuery` incorrectly?

https://github.com/ryancheung/RecastSharp/blob/b91940fc297cad64b58a96beb9e05c824a4679b6/src/Detour/DetourNode.cs#L32-L42

**Comment by ryancheung** [comment]
Thanks! This bug is caused by code line misplacement.

**Comment by ryancheung** [comment]
This repo is initially ported from the original c++ version. Lots of code may crash, it needs more further tests and fixes.
